name: Auto Magisk Files Provider
on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
  #  branches:
  #    - master
  schedule:
    - cron: 0 */8 * * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Download Json
        run: |
          wget https://raw.githubusercontent.com/topjohnwu/magisk_files/master/beta.json -O beta.json
          wget https://raw.githubusercontent.com/topjohnwu/magisk_files/master/stable.json -O stable.json
          wget https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/canary.json -O canary.json

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "raw.githubusercontent.com"
          replace: "raw.fastgit.org"
          include: ".json"

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "github.com"
          replace: "download.fastgit.org"
          include: ".json"

      - name: Commit files
        run: |
          {
              git config --local user.email "1844766234@qq.com"
              git config --local user.name "RC1844"
              git commit -m "$(date "+%Y-%m-%d %H:%M:%S")" -a
              if [ $? -eq 0 ]; then
                  echo "Add Update."
              else
                  echo "No Update."
              fi
          } || {
              echo "Execution Failed"
              exit 1
          }

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
