name: Auto Magisk Files Provider
on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: 0 */8 * * *
  watch:
    types: [started]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Json
        run: |
          wget https://raw.githubusercontent.com/topjohnwu/magisk_files/master/beta.json -O beta.json
          wget https://raw.githubusercontent.com/topjohnwu/magisk_files/master/stable.json -O stable.json
          wget https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/debug.json -O debug.json
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "https://raw.githubusercontent.com"
          replace: "https://download.fastgit.org"
          include: "*.json"
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "https://github.com"
          replace: "https://download.fastgit.org"
          include: "*.json"
